name: wechat_assets_picker_demo
description: The demo project for the wechat_assets_picker package.
version: 6.0.0-dev.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wechat_assets_picker:
    path: ../
  wechat_camera_picker:
    git:
      url:  https://github.com/GanTongZhen/flutter_wechat_camera_picker.git

  extended_image: ^4.0.0
  package_info_plus: ^1.0.3
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
