name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 6.0.0-dev.3
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^4.1.0
  photo_manager:
    git:
      url: https://github.com/GanTongZhen/flutter_photo_manager.git
  provider: ^5.0.0
  video_player: ^2.1.6
